### ISSUE TITLE
gkd更新

### ISSUE THREAD

**Issue by chayZeng** [fenghaojiang/Interview-Review#1]

**Comment by chayZeng** [comment]
我只能说，祝江宝早日嗯到白富美

**Comment by fenghaojiang** [comment]
> 我只能说，祝江宝早日嗯到白富美


> 我只能说，祝江宝早日嗯到白富美

嗯了，嗯了个杰宝了

**Comment by chayZeng** [comment]
abstract class Jb {
    float smallRadius = 0.5f;
    float shortLength = 5f;
    
    abstract void en() {
        Log.i("江宝", "嗯到了");
    }
}
